namespace: mlops-stock

nginx:
  image: ghcr.io/adrianbl17/mlops-stock-nginx:latest
  replicas: 1
  nodePort: 30000

api:
  image: ghcr.io/adrianbl17/mlops-stock-api:latest
  replicas: 1

postgres:
  image: postgres:17.0-alpine
  storage: 1Gi
  hostPath: /tmp/postgres-data
  user: stock_user
  db: predictions