$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
description: Custom environment for LSTM training
name: aml-stock-training-cli
version: 0.1.0

conda_file: ../components/training/conda.yaml
image: mcr.microsoft.com/azureml/openmpi5.0-ubuntu24.04:latest
os_type: linux

tags:
  tensorflow: 2.15.0
  scikit-learn: 1.6.1
