name: Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - 'api/**'
      - 'nginx/**'
      - 'helm/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy data and models to workspace
        run: |
          Copy-Item -Recurse "C:\Users\adria\Documents\4de sem\MLOps\mlops-stock-prediction\api\data" "${{ github.workspace }}\api\data"
          Copy-Item -Recurse "C:\Users\adria\Documents\4de sem\MLOps\mlops-stock-prediction\api\models" "${{ github.workspace }}\api\models"
          Copy-Item "C:\Users\adria\Documents\4de sem\MLOps\mlops-stock-prediction\.env" "${{ github.workspace }}\.env"

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        run: |
          docker build -t ghcr.io/adrianbl17/mlops-stock-api:latest -t ghcr.io/adrianbl17/mlops-stock-api:${{ github.sha }} ./api
          docker push ghcr.io/adrianbl17/mlops-stock-api:latest
          docker push ghcr.io/adrianbl17/mlops-stock-api:${{ github.sha }}

      - name: Build and push NGINX image
        run: |
          docker build -t ghcr.io/adrianbl17/mlops-stock-nginx:latest -t ghcr.io/adrianbl17/mlops-stock-nginx:${{ github.sha }} ./nginx
          docker push ghcr.io/adrianbl17/mlops-stock-nginx:latest
          docker push ghcr.io/adrianbl17/mlops-stock-nginx:${{ github.sha }}

      - name: Create namespace if needed
        run: kubectl create namespace mlops-stock --dry-run=client -o yaml | kubectl apply -f - --kubeconfig "$env:USERPROFILE\.kube\config"

      - name: Create secret if needed
        run: kubectl create secret generic stock-secret --from-env-file=.env -n mlops-stock --dry-run=client -o yaml | kubectl apply -f - --kubeconfig "$env:USERPROFILE\.kube\config"

      - name: Helm upgrade
        run: helm upgrade --install stock-prediction ./helm/stock-prediction --namespace mlops-stock --set api.image=ghcr.io/adrianbl17/mlops-stock-api:${{ github.sha }} --set nginx.image=ghcr.io/adrianbl17/mlops-stock-nginx:${{ github.sha }} --kubeconfig "$env:USERPROFILE\.kube\config"

      - name: Verify deployment
        run: kubectl get pods -n mlops-stock --kubeconfig "$env:USERPROFILE\.kube\config"